### ISSUE TITLE
Support Web Platform Installer 5.0

### ISSUE THREAD

**Issue by neoscribe1** [chef-cookbooks/webpi#21]
I used webpi on a server that already had Web Platform Installer 5.0 on it, but it failed because webpi cannot install 4.5. 
Can you fix this so that 
1) I can specify which version to install (4.5 or 5.0 or x.x)
2) I can specify whether or not to ignore "1603" success code which says "a newer version is already installed"

**Comment by tas50** [comment]
5.0 is going to be the new default in the 2.0 release of this cookbook.  I'm going to release it tomorrow.  Sorry this has taken so long.

https://github.com/chef-cookbooks/webpi/tree/no_zip

**Comment by HaroonSaid** [comment]
Update on WepPI 5.0 release?
