### ISSUE TITLE
No resource or method named 'cached_file' error

### ISSUE THREAD

**Issue by casey-robertson** [chef-cookbooks/webpi#31]
### Cookbook version
4.1.0

### Chef-client version
12.19.36

### Platform Details
Windows 2012 R2

### Scenario:
Attempting to run webpi::install-msi recipe and have the webpi bits downloaded and installed in preparation for installation of Service Bus 1.1

### Steps to Reproduce:
Create a cookbook/recipe that depends on 'webpi' and 'windows'.  Create default recipe that includes webpi::install-msi.  Converge the default recipe (which should download and install the webpi .msi.

### Expected Result:
Expect that Web Platform Installer is installed to the system and can be called via the webpi_product resource to install Service Bus.  

### Actual Result:
Compilation of the cookbook fails - error is:

`NoMethodError
       -------------
       No resource or method named `cached_file' for `Chef::Recipe "install-msi"'`

Research shows that the latest version of the windows cookbook (3.0.2) made a change that breaks current webpi cookbook which calls the cached_file method.  This method appears to have been deleted from the windows_helper.rb via this commit:

[https://github.com/chef-cookbooks/windows/commit/bae551985ee9cd3fe5431f283ee7487a522dfc65](url)

Current resolution is to add `depends 'windows', '= 3.0.1'` 
This version of the windows cookbook works.

**Comment by tas50** [comment]
This has been resolved in the 4.1.1 release. Thanks for the report
