### ISSUE TITLE
Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404

### ISSUE THREAD

**Issue by mmclane** [chef-cookbooks/webpi#37]
### Cookbook version
1.2.9

### Chef-client version
12

### Platform Details
windows 2012r2

### Scenario:
I am getting the following error:  Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404

When I try to browse to that URL it is indeed invalid.

### Steps to Reproduce:
1517935130,,ui,message,    amazon-ebs: [2018-02-06T11:38:49-05:00] INFO: Processing webpi_product[WDeployNoSMO] action install (webdeploymenttoolkit::default line 8)
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: ================================================================================
1517935136,,ui,message,    amazon-ebs: Error executing action `install` on resource 'webpi_product[WDeployNoSMO]'
1517935136,,ui,message,    amazon-ebs: ================================================================================
1517935136,,ui,message,    amazon-ebs:
1517935136,,ui,message,    amazon-ebs: Mixlib::ShellOut::ShellCommandFailed
1517935136,,ui,message,    amazon-ebs: ------------------------------------
1517935136,,ui,message,    amazon-ebs: Expected process to exit with [0%!(PACKER_COMMA) 42]%!(PACKER_COMMA) but received '-1'
1517935136,,ui,message,    amazon-ebs: ---- Begin output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: STDOUT: The software that you obtain using the Web Plaform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
1517935136,,ui,message,    amazon-ebs: .  \r .. \r ...\r    \r    \rUnexpected exception occurred
1517935136,,ui,message,    amazon-ebs: Url 'https://www.microsoft.com/en-us/web/webpi/4.6/webproductlist.xml' returned HTTP status code: 404
1517935136,,ui,message,    amazon-ebs: STDERR:
1517935136,,ui,message,    amazon-ebs: ---- End output of "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log ----
1517935136,,ui,message,    amazon-ebs: Ran "C:\Program Files/Microsoft/Web Platform Installer/WebpiCmd.exe" /Install /products:WDeployNoSMO /suppressreboot /accepteula /Log:c:\chef\cache/WebPI.log returned -1
1517935136,,ui,message,    amazon-ebs:

### Expected Result:
It should install

**Comment by iennae** [comment]
I talked to @mmclane about this issue. The source cookbook that they were using was https://github.com/wildbillcat-cookbooks/webdeploymenttoolkit. The pinned version of the cookbook that cookbook uses of this cookbook is a really old version, (1.2.8).
